name: serenya_app
description: Serenya AI Health Agent mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  sqflite_common_ffi: ^2.3.0+2
  sqlite3_flutter_libs: ^0.5.18
  path: ^1.8.3
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  # SQLCipher encryption for local database
  sqflite_sqlcipher: ^2.2.1
  # Biometric authentication
  local_auth: ^2.1.6
  # HKDF key derivation
  cryptography: ^2.5.0
  # Enhanced Navigation and State Management
  go_router: ^12.1.3
  # Enhanced Testing Support
  equatable: ^2.0.5
  # Enhanced HTTP Client
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  # Enhanced Testing Framework
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter
  # Code Generation
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true