// Mocks generated by Mockito for TimelinePreloadService tests
// Manual implementation since build_runner is not available

import 'package:mockito/mockito.dart' as i1;
import 'package:serenya_app/core/providers/health_data_provider.dart' as i2;
import 'package:serenya_app/models/local_database_models.dart' as i3;

class MockHealthDataProvider extends i1.Mock implements i2.HealthDataProvider {
  @override
  bool get hasMoreData =>
      (super.noSuchMethod(
        Invocation.getter(#hasMoreData),
        returnValue: true,
      ) as bool);

  @override
  List<i3.SerenyaContent> get content =>
      (super.noSuchMethod(
        Invocation.getter(#content),
        returnValue: <i3.SerenyaContent>[],
      ) as List<i3.SerenyaContent>);

  @override
  void setPageSize(int size) =>
      (super.noSuchMethod(
        Invocation.method(#setPageSize, [size]),
        returnValueForMissingStub: null,
      ));

  @override
  Future<void> preloadNextBatch({i3.ContentType? contentType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #preloadNextBatch,
          [],
          {#contentType: contentType},
        ),
        returnValue: Future<void>.value(),
      ) as Future<void>);
}